language: node_js
node_js:
  - "8"
before_install:
  - npm i -g npm@latest
  - npm install
cache:
  directories:
    - "node_modules"
notifications:
  email:
    recipient:
      - alexandre.saison@omnilog.fr
    on_success: change # default: change
    on_failure: always # default: always
